POST http://localhost:4000/api/v1/roles HTTP/1.1
Content-Type: application/json

{
  "name": "test"
}

### Get all
GET http://localhost:4000/api/v1/roles HTTP/1.1

### Get by id
GET http://localhost:4000/api/v1/roles/67b389a34d78f16b04c8dd64 HTTP/1.1

### Update
PUT http://localhost:4000/api/v1/roles/67b389a34d78f16b04c8dd64 HTTP/1.1
Content-Type: application/json

{
  "name": "Test"
}

### Delete
DELETE http://localhost:4000/api/v1/roles/67b389a34d78f16b04c8dd64 HTTP/1.1